name: project_akhir_donasi_android
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  midtrans_sdk: ^0.4.0
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.8
  dotenv: ^4.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  google_fonts: ^6.2.1
  http: ^1.3.0
  image_picker: ^0.8.7+4
  intl: ^0.18.1
  logo: ^1.2.1
  midtrans: ^0.1.0
  path: ^1.8.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  url_launcher: ^6.1.10
  video_player: ^2.7.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logojticare.png
    - assets/jticarebiru.png
    - assets/home.png
    - assets/bell.png
    - assets/give.png
    - assets/profile.png
    - assets/bell_warna.png
    - assets/give_warna.png
    - assets/profile_warna.png
    - assets/home_warna.png
    - assets/ic_donasi.png
    - assets/banjir.png
    - assets/kebakaran.jpg
    - assets/gempa.jpg
    - assets/panti.jpg
    - assets/profile_dummy.webp
    - assets/profile_dummy2.png
    - assets/splash1.png
    - assets/splash2.png
    - assets/splash3.png
    - assets/gif/splashgif.gif

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/POPPINS-REGULAR.TTF
        - asset: assets/fonts/POPPINS-BOLD.TTF
          weight: 700
