name: project_akhir_donasi_android
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  logo: ^1.2.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logojticare.png
    - assets/jticarebiru.png
    - assets/home.png
    - assets/bell.png
    - assets/give.png
    - assets/profile.png
    - assets/bell_warna.png
    - assets/give_warna.png
    - assets/profile_warna.png
    - assets/home_warna.png
    - assets/ic_donasi.png
    - assets/banjir.png
    - assets/kebakaran.jpg
    - assets/gempa.jpg
    - assets/panti.jpg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/POPPINS-REGULAR.TTF
        - asset: assets/fonts/POPPINS-BOLD.TTF
          weight: 700
